name: 🤖 Safe Profile Auto-Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'scripts/**' ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: 🚀 Update Profile README (Safe Mode)
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 🤖 Run safe README update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/update_readme_safe.py

    - name: 📊 Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: 💾 Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "🤖 Auto-update: Statistiques et projets mis à jour ($(date '+%Y-%m-%d %H:%M:%S UTC'))" || exit 0
        git push origin main

    - name: ✅ Success notification
      if: steps.git-check.outputs.changes == 'true'
      run: |
        echo "✅ README mis à jour avec succès !"
        echo "📅 Timestamp: $(date '+%Y-%m-%d %H:%M:%S UTC')"
        echo "🔧 Mode: Safe Update - Contenu manuel préservé"
        
    - name: ℹ️ No changes notification
      if: steps.git-check.outputs.changes != 'true'
      run: |
        echo "ℹ️ Aucune modification détectée - README déjà à jour"
        echo "📅 Vérification: $(date '+%Y-%m-%d %H:%M:%S UTC')"
